### ISSUE TITLE
Issue with @microsoft.azure/literate package

### ISSUE THREAD

**Issue by dsgouda** [Azure/perks.node#5]
When using the `@microsoft.azure/literate` package in the CI build scripts for rest spec repo, ran into this [error](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/261175730) may have to do with case sensitivity requirement on the travis machines.
@fearthecowboy can you please fix and republish this.

**Comment by fearthecowboy** [comment]
Fixed and package pushed to `@microsoft.azure/literate@1.0.21`
